# Network configuration
priority_networks = 172.20.80.0/24

# Storage
storage_root_path = /opt/apache-doris/be/storage

# Performance
be_port = 9060
webserver_port = 8040
heartbeat_service_port = 9050
brpc_port = 8060

# Disable swap
enable_swap = false

aws_s3_region = us-east-1
aws_s3_endpoint = http://minio:9000
aws_s3_access_key = astro
aws_s3_secret_key = Makeclean@123
aws_s3_use_path_style = true

priority_networks = 172.20.80.0/24
