brpc_listen_port = 5000
brpc_num_threads = -1

# fdb cluster connection string (will be populated dynamically)
fdb_cluster=docker:docker@172.20.80.20:4500

# cloud_unique_id used for creating expansion of resource
cloud_unique_id = 172.20.80.21

# logging
log_dir = ./log
